CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
GRAPH_TOKEN_INDEX = -200
DEFAULT_GRAPH_TOKEN = "<graph>"
DEFAULT_GRAPH_START_TOKEN = "<GH>"
DEFAULT_GRAPH_END_TOKEN = "</GH>"
DEFAULT_GRAPH_PAD_ID = -500

TEMPLATE_ND = "nd"  # 原有的树形采样
TEMPLATE_RW = "rw"  # 新增的Random Walk采样
DEFAULT_TEMPLATE = TEMPLATE_ND  # 默认使用ND模板